[2022-08-18 17:26:47,417] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-18T17:26:40.733006+00:00 [queued]>
[2022-08-18 17:26:47,427] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-18T17:26:40.733006+00:00 [queued]>
[2022-08-18 17:26:47,427] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 17:26:47,427] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-18 17:26:47,427] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 17:26:47,449] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data> on 2022-08-18 17:26:40.733006+00:00
[2022-08-18 17:26:47,457] {standard_task_runner.py:52} INFO - Started process 169 to run task
[2022-08-18 17:26:47,461] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'load_data', 'manual__2022-08-18T17:26:40.733006+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpdor8kqj2', '--error-file', '/tmp/tmpzet80w9h']
[2022-08-18 17:26:47,462] {standard_task_runner.py:80} INFO - Job 100: Subtask load_data
[2022-08-18 17:26:47,539] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.load_data manual__2022-08-18T17:26:40.733006+00:00 [running]> on host b4d24a91aa11
[2022-08-18 17:26:47,683] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T17:26:40.733006+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T17:26:40.733006+00:00
[2022-08-18 17:26:54,072] {python.py:173} INFO - Done. Returned value was: None
[2022-08-18 17:26:54,098] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Satellite_Data, task_id=load_data, execution_date=20220818T172640, start_date=20220818T172647, end_date=20220818T172654
[2022-08-18 17:26:54,151] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-18 17:26:54,192] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
