[2022-08-19 18:04:17,085] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data scheduled__2022-08-18T16:32:25.188706+00:00 [queued]>
[2022-08-19 18:04:17,110] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data scheduled__2022-08-18T16:32:25.188706+00:00 [queued]>
[2022-08-19 18:04:17,111] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:04:17,111] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-19 18:04:17,111] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:04:17,146] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data> on 2022-08-18 16:32:25.188706+00:00
[2022-08-19 18:04:17,161] {standard_task_runner.py:52} INFO - Started process 103 to run task
[2022-08-19 18:04:17,175] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'load_data', 'scheduled__2022-08-18T16:32:25.188706+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpdelzs85m', '--error-file', '/tmp/tmphxu3zawa']
[2022-08-19 18:04:17,176] {standard_task_runner.py:80} INFO - Job 117: Subtask load_data
[2022-08-19 18:04:17,299] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.load_data scheduled__2022-08-18T16:32:25.188706+00:00 [running]> on host 3a5c2d0be6af
[2022-08-19 18:04:17,510] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T16:32:25.188706+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-18T16:32:25.188706+00:00
[2022-08-19 18:04:27,316] {python.py:173} INFO - Done. Returned value was: None
[2022-08-19 18:04:27,337] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Satellite_Data, task_id=load_data, execution_date=20220818T163225, start_date=20220819T180417, end_date=20220819T180427
[2022-08-19 18:04:27,379] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 18:04:27,417] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
