[2022-08-19 19:05:07,314] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-19T19:05:02.703881+00:00 [queued]>
[2022-08-19 19:05:07,328] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-19T19:05:02.703881+00:00 [queued]>
[2022-08-19 19:05:07,328] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 19:05:07,328] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-19 19:05:07,328] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 19:05:07,371] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data> on 2022-08-19 19:05:02.703881+00:00
[2022-08-19 19:05:07,378] {standard_task_runner.py:52} INFO - Started process 182 to run task
[2022-08-19 19:05:07,380] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'load_data', 'manual__2022-08-19T19:05:02.703881+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp4r3zba1l', '--error-file', '/tmp/tmp3mzii48e']
[2022-08-19 19:05:07,380] {standard_task_runner.py:80} INFO - Job 135: Subtask load_data
[2022-08-19 19:05:07,472] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.load_data manual__2022-08-19T19:05:02.703881+00:00 [running]> on host cd3dd6eb44d2
[2022-08-19 19:05:07,738] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T19:05:02.703881+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T19:05:02.703881+00:00
[2022-08-19 19:05:09,981] {python.py:173} INFO - Done. Returned value was: None
[2022-08-19 19:05:10,004] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Satellite_Data, task_id=load_data, execution_date=20220819T190502, start_date=20220819T190507, end_date=20220819T190510
[2022-08-19 19:05:10,079] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 19:05:10,134] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
