[2022-08-19 18:04:20,069] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data manual__2022-08-19T02:40:48.850961+00:00 [queued]>
[2022-08-19 18:04:20,081] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data manual__2022-08-19T02:40:48.850961+00:00 [queued]>
[2022-08-19 18:04:20,081] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:04:20,081] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-19 18:04:20,081] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:04:20,258] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): using_pyspark_to_analyze_streaming_data> on 2022-08-19 02:40:48.850961+00:00
[2022-08-19 18:04:20,267] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2022-08-19 18:04:20,271] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'using_pyspark_to_analyze_streaming_data', 'manual__2022-08-19T02:40:48.850961+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpqe426d79', '--error-file', '/tmp/tmpm5t7fihz']
[2022-08-19 18:04:20,272] {standard_task_runner.py:80} INFO - Job 120: Subtask using_pyspark_to_analyze_streaming_data
[2022-08-19 18:04:20,627] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data manual__2022-08-19T02:40:48.850961+00:00 [running]> on host 3a5c2d0be6af
[2022-08-19 18:04:20,905] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=using_pyspark_to_analyze_streaming_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T02:40:48.850961+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T02:40:48.850961+00:00
[2022-08-19 18:04:20,906] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-19 18:04:20,907] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/L/Programming/dataEng/spaceApp/Streaming/read_data.py']
[2022-08-19 18:04:20,920] {subprocess.py:85} INFO - Output:
[2022-08-19 18:04:21,057] {subprocess.py:92} INFO - python3: can't open file '/home/L/Programming/dataEng/spaceApp/Streaming/read_data.py': [Errno 2] No such file or directory
[2022-08-19 18:04:21,060] {subprocess.py:96} INFO - Command exited with return code 2
[2022-08-19 18:04:21,088] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-08-19 18:04:21,097] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Satellite_Data, task_id=using_pyspark_to_analyze_streaming_data, execution_date=20220819T024048, start_date=20220819T180420, end_date=20220819T180421
[2022-08-19 18:04:21,135] {standard_task_runner.py:97} ERROR - Failed to execute job 120 for task using_pyspark_to_analyze_streaming_data (Bash command failed. The command returned a non-zero exit code 2.; 109)
[2022-08-19 18:04:21,164] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-19 18:04:21,217] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
